### ISSUE TITLE
Deal better with the xentrace temporary file

### ISSUE THREAD

**Issue by dfaggioli** [lory9894/xen_kvm_compare#3]
https://github.com/lory9894/xen_kvm_compare/blob/c6668a4102e559abff4c3c7c6adb4cf1c7b49f63/watch-xentrace.sh#L17

Dealing with the fact that `xentrace` can only create an output file in this way, i.e., by running `xentrace` itself in background and `tail`-ing the file is ok.

However:

1. the `xentrace.bin` file is a temporary one, so let's avoid clashes with existing file names, etc. One way of doing that is creating it with `mktemp`, e.g.: `tmpfile=$(mktemp --dry-run mmtests-xentrace-XXXXXX.bin)`. And then you have a string in `$tmpfile` that you can use as the file name of the temporary binary xentrace file

2. the temp. file should be removed at the end. Basically, we just have to `rm` it, but of course we can do that only when we're sure the monitor has been stopped. I think that `monitors/watch-numad.sh` can be a good example of how to achieve that (although, it does not delete anything itself, but the waiting part is there...)

**Comment by lory9894** [comment]
Thanks.
Considering point 2, there is no need to tail the output of xentrace, I can simply cat it before removing it. I'll fix it as soon as possible

**Comment by lory9894** [comment]
I added interruption handling for SIGINT as well as SIGTERM, i'm not sure if it's necessary
